### ISSUE TITLE
Refactor and update plugin documentation

### ISSUE THREAD

**Issue by robrap** [openedx/edx-django-utils#276]
A/C

- [ ] Finish and merge https://github.com/openedx/edx-django-utils/pull/278/files?diff=unified&w=1

I captured a number of proposed changes to the docs in the form of a PR (closed, but not completed). This ticket would be about finishing out the TODOs, getting this reviewed and landed.

See https://github.com/openedx/edx-django-utils/pull/278/files?diff=unified&w=1

**Comment by rgraber** [comment]
Finishing out the TODO for telling people how to easily check if plugins are enabled turns out to be a little more involved since we don't really have an easy way right now. My proposal would be to make a sample plugin in edx-arch-experiments and tell people to pip install it into their IDA, then check to make sure all the urls and management commands and whatnot are there. 
In any case, for now we just suggest checking that the code to extend INSTALLED_APPS is there. If we want to make a new sample plugin , or otherwise update that documentation, it can be a separate issue.

**Comment by robrap** [comment]
> In any case, for now we just suggest checking that the code to extend INSTALLED_APPS is there.

Agreed. Let's do something lightweight. I just wanted someone to know whether or not they needed to read the full docs.
